apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
  namespace: vprofile
  labels:
    app: vproapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vproapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      imagePullSecrets:
        - name: ecr-cred
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      initContainers:
        - name: copy-war
          image: public.ecr.aws/d5v9o1s2/vprofile-app:v3.1
          command: ['sh', '-c', 'cp -r /usr/local/tomcat/webapps.orig/* /usr/local/tomcat/webapps/ || cp -r /usr/local/tomcat/webapps/* /mnt/webapps/']
          volumeMounts:
            - name: tomcat-webapps
              mountPath: /mnt/webapps
          securityContext:
            runAsUser: 1001
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      containers:
        - name: vproapp
          image: public.ecr.aws/d5v9o1s2/vprofile-app:v3.1
          
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1001
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          volumeMounts:
            - name: tomcat-temp
              mountPath: /usr/local/tomcat/temp
            - name: tomcat-work
              mountPath: /usr/local/tomcat/work
            - name: tomcat-logs
              mountPath: /usr/local/tomcat/logs
            - name: tomcat-webapps
              mountPath: /usr/local/tomcat/webapps
            - name: tomcat-conf
              mountPath: /usr/local/tomcat/conf/Catalina
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: vprofile-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: vprofile-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: vprofile-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: vprofile-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vprofile-secrets
                  key: DB_PASSWORD
            - name: MC_HOST
              valueFrom:
                configMapKeyRef:
                  name: vprofile-config
                  key: MC_HOST
            - name: MC_PORT
              valueFrom:
                configMapKeyRef:
                  name: vprofile-config
                  key: MC_PORT
            - name: RMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: vprofile-config
                  key: RMQ_HOST
            - name: RMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: vprofile-config
                  key: RMQ_PORT
            - name: RMQ_USER
              valueFrom:
                secretKeyRef:
                  name: vprofile-secrets
                  key: RMQ_USER
            - name: RMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vprofile-secrets
                  key: RMQ_PASSWORD
      volumes:
        - name: tomcat-temp
          emptyDir: {}
        - name: tomcat-work
          emptyDir: {}
        - name: tomcat-logs
          emptyDir: {}
        - name: tomcat-webapps
          emptyDir: {}
        - name: tomcat-conf
          emptyDir: {}
