apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vprodb
  namespace: vprofile
  labels:
    app: vprodb
spec:
  serviceName: vprodb-service
  replicas: 1
  selector:
    matchLabels:
      app: vprodb
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      securityContext:
          seccompProfile:
            type: RuntimeDefault
          runAsNonRoot: true
          runAsUser: 999
          fsGroup: 999
      containers:
      - name: mysql
        image: 772683617793.dkr.ecr.us-east-1.amazonaws.com/java-proj:db01
        ports:
        - containerPort: 3306
          name: mysql
        securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
          
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vprofile-secrets
              key: DB_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: vprofile-config
              key: DB_NAME
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: vprofile-secrets
              key: DB_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vprofile-secrets
              key: DB_PASSWORD
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: init-db
          mountPath: /docker-entrypoint-initdb.d
        livenessProbe:
          exec:
            command:
            - bash
            - -c
            - mysqladmin ping -h localhost -u root -p$MYSQL_ROOT_PASSWORD
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - bash
            - -c
            - mysql -h localhost -u root -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1'
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
        # Probes removed for stability
      volumes:
      - name: init-db
        configMap:
          name: vprodb-init
      - name: mysql-data
        emptyDir: {}
