apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprocache
  namespace: vprofile
  labels:
    app: vprocache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprocache
  template:
    metadata:
      labels:
        app: vprocache
    spec:
      securityContext:
          seccompProfile:
            type: RuntimeDefault
          runAsNonRoot: true
          runAsUser: 1001
          fsGroup: 1001
      containers:
      - name: memcached
        image: memcached:1.6-alpine
        ports:
        - containerPort: 11211
          name: memcached
        securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
          
        livenessProbe:
          tcpSocket:
            port: 11211
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 11211
          initialDelaySeconds: 5
          periodSeconds: 5
