apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
  namespace: vprofile
spec:
  type: NodePort
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3 hours
  selector:
    app: vproapp
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30001
    protocol: TCP
    name: http