apiVersion: v1
kind: Service
metadata:
  name: vprodb-service
  namespace: vprofile
spec:
  type: ClusterIP
  selector:
    app: vprodb
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: mysql
