apiVersion: v1
kind: Service
metadata:
  name: vpromq-service
  namespace: vprofile
spec:
  type: ClusterIP
  selector:
    app: vpromq
  ports:
  - port: 5672
    targetPort: 5672
    protocol: TCP
    name: amqp
  - port: 15672
    targetPort: 15672
    protocol: TCP
    name: management
